spring.application.name=spring

spring.jpa.hibernate.ddl-auto=validate

#LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
## should be in env tbh
spring.datasource.username=postgres
spring.datasource.password=postgres
